Update doc
traitecoevo/APCalign pull request #192
Opened 2024-04-18 00:40 UTC by fontikar

Addresses Reviewer 1's suggestion on how to cite the version of the package as well as the taxonomic resources.

Changes made

- An article on the website walking a reader through how to get the package version and version of the taxonomic resource
- I have added a citation file so folks can cite the package and eventually the research article when in press
- Exported default_version() so users can see what version of taxonomic resources is being used in alignment and update.
- Updated website yml so new article will show
- While I was updating website, I fixed some bugs about missing images in data_provider article and the name to call the 'updating-taxon-names" vignette
- Have bumped version number and updated NEWS.md accordingly

2024-04-18 03:46 UTC, dfalster requested changes
Nice, some suggested additions!

2024-04-18 03:46 UTC, dfalster commented on _pkgdown.yml
> +        href: articles/articles/data-providers.html
surely wrong?

2024-04-18 03:46 UTC, dfalster commented on inst/CITATION
> +  bibtype  = "Manual",
Shall we change this to the preprint? https://www.biorxiv.org/content/10.1101/2024.02.02.578715v1

2024-04-18 03:46 UTC, dfalster commented on vignettes/articles/reproducibility.Rmd
> +We recommend to always use `stable_or_current_data = "stable"` if you want your taxonomic alignment and update to be reproducible. The preset value is `stable_or_current_data = "stable"`. These stati
```suggestion
If you want your taxonomic alignment and update to be reproducible, we recommend to always use `stable_or_current_data = "stable"`. The default value is `stable_or_current_data = "stable"`. These static downloads are version controlled and stored in our repository as [releases](https://github.com/traitecoevo/APCalign/releases). 
```

2024-04-18 03:46 UTC, dfalster commented on vignettes/articles/reproducibility.Rmd
> +```
This is good, but can we add something here that shows how to the pass the resources into the successive functions?

2024-04-18 03:46 UTC, dfalster commented on vignettes/articles/reproducibility.Rmd
> +```
Also, show the capability to save the results to file and reuse those

2024-04-18 03:53 UTC, fontikar commented on _pkgdown.yml
> +        href: articles/articles/data-providers.html
Nope! Trust ;) I thought I was going crazy. Removing the second articles breaks the image file path.

2024-04-18 03:54 UTC, fontikar commented on inst/CITATION
> +  bibtype  = "Manual",
Great idea! Will update the authors according too!

2024-04-18 04:06 UTC, fontikar commented on vignettes/articles/reproducibility.Rmd
> +```
> Also, show the capability to save the results to file and reuse those

Although our functions have the option to save output of alignments and updates. I don't actually think it currently works. 

```
aligned_updated_taxa <- create_taxonomic_update_lookup(gbif_lite$species, resources = resources, output = "ignore/")
Checking alignments of 121 taxa

  -> 0 names already matched; 0 names checked but without a match; 121 taxa yet to be checked
Error in open.connection(3L, "wb") : cannot open the connection
In addition: Warning messages:
1: In file(path) :
  'raw = FALSE' but '/Users/fontikar/Dropbox/0 - Job/APCalign/ignore' is not a regular file
2: In open.connection(3L, "wb") :
  cannot open file '/Users/fontikar/Dropbox/0 - Job/APCalign/ignore': Is a directory
  ```
  
  This was on [the backlog ](https://github.com/traitecoevo/APCalign/issues/140) but got deprioritised. 
  
  Should we remove this functionality for now? Thoughts @dfalster

2024-04-22 02:55 UTC, fontikar commented on vignettes/articles/reproducibility.Rmd
> +```
Addressed in https://github.com/traitecoevo/APCalign/issues/194 and https://github.com/traitecoevo/APCalign/pull/198

2024-04-22 02:57 UTC, merged